# Author : Shantanu Zadbuke
version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-service
    env_file:
      - .env
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    volumes:
      - ./:/app
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8080} --reload"
    restart: unless-stopped


